//
// Created by MEHMET on 9.03.2024.
//

#ifndef NEURAL_NETWORK_FROM_STCRATCH_ACTIVATIONFUNCTIONS_H
#define NEURAL_NETWORK_FROM_STCRATCH_ACTIVATIONFUNCTIONS_H

class activationFunctions{
public:

private:
};

#endif //NEURAL_NETWORK_FROM_STCRATCH_ACTIVATIONFUNCTIONS_H

